### ISSUE TITLE
Migrate to static site generator

### ISSUE THREAD

**Issue by breadloaf64** [breadloaf64/PersonalWebsite#13]
Pick a SSG to use, then reimplement the site using it! This will help with reusable stuff like navbar and blog

**Comment by breadloaf64** [comment]
Let's use [Astro](https://astro.build/)!

**Comment by pmarsh-scottlogic** [comment]
This work will happen on the branch Astro-Refactor. There will be PRs going into that branch to break development into chunks

**Comment by breadloaf64** [comment]
Done #25
